sources:
  - name: s1
    database: dev_db
    schema: dev_schema
    tables:
      - name: customers
      - name: payment
      - name: orders
      - name: t_customers
      - name: t_nation    
      - name: t_ticket_info        
      - name: emp       
      - name: t_audit_log      
              